/* PLOP_INJECT_PAGES_EXPORT */
import '../i18n';
export { TableSearch } from './profile/sub-pages/table-search/table-search';
export { OtpComponentLinkGuardian } from './register/components/link-guardian/otp-component-link-guardian';
export { RelationProof } from './register/components/link-guardian/relation-proof';
export { Home } from './home';
export { PageNotFound } from './page-not-found';
export { LoginTrack } from './login/sub-pages/login-track/login-track';
export { LoginRecovery } from './login/sub-pages/login-recovery/login-recovery';
export { FacilityLogin } from './facility-login';
export { FacilityGenerate } from './facility-login/sub-pages/facility-generate/facility-generate';
export { LoginAbhaNumber } from './login/sub-pages/login-abha-number/login-abha-number';
export { LoginMobileOtpForm } from './login/components/login-via-mobile/mobile-otp-form';
export { Login } from './login';
// export { ProfileDrawer } from './profile/components/profile-drawer/profile-drawer';
export { Profile } from './profile';
export { UserProfile } from './user-profile';
export { LinkAbhaAddress } from './register/components/link-abha-address/link-abha-address';
export { RegisterDrivingLicence } from './register/sub-pages/register-driving-licence/register-driving-licence';
export { Register } from './register';
export { LinkGuardian } from '../pages/register/components/link-guardian/link-guardian';
